{% set name = "uutils-coreutils" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uutils/coreutils/archive/{{ version }}.tar.gz
  sha256: a3295f7ec0600f379ec829649fcedc0432f493cbfc64ad10a1f9b6c52e874387
  patches:
    - 0001-FIX_BUILDDIR_IN_MAKE.patch  # [not win]
    # Fixes long command and quotes problems
    - 0002-SHORTEN_SH_COMMANDS.patch

build:
  number: 0
  ignore_run_exports:
    - libstdcxx-ng  # [linux]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [not linux]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make
    - cargo-bundle-licenses
  run_constrained:
    - coreutils ==999999999
    - gnu-coreutils ==999999999

test:
  commands:
    - coreutils --help
    - cat --help

about:
  home: https://github.com/uutils/coreutils
  summary: Cross-platform Rust rewrite of the GNU coreutils
  description: |
    uutils is an attempt at writing universal (as in cross-platform) CLI utilities in Rust.
    uutils aims to work on as many platforms as possible,
    to be able to use the same utils on Linux, Mac, Windows and other platforms.
    This ensures, for example, that scripts can be easily transferred between platforms.
    Rust was chosen not only because it is fast and safe,
    but is also excellent for writing cross-platform code.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://uutils.github.io/user/
  dev_url: https://github.com/uutils/coreutils

extra:
  recipe-maintainers:
    - sshockwave
