{% set name = "uutils-coreutils" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uutils/coreutils/archive/{{ version }}.tar.gz
  sha256: 55c528f2b53c1b30cb704550131a806e84721c87b3707b588a961a6c97f110d8
  patches:
    # Fixes long command and quotes problems
    - 0002-SHORTEN_SH_COMMANDS.patch
    - 0003-DISABLE_SELINUX.patch  # [not linux]

build:
  number: 0
  ignore_run_exports:
    - libstdcxx  # [linux]
    - libstdcxx-ng  # [linux]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ cdt('libselinux-devel') }}  # [linux]
    - make
    - cargo-bundle-licenses
    - libclang  # [linux]
  run_constrained:
    - coreutils ==999999999
    - gnu-coreutils ==999999999
    - m2-coreutils ==999999999

test:
  commands:
    - coreutils --help
    - cat --help

about:
  home: https://uutils.github.io/coreutils/
  summary: Cross-platform Rust rewrite of the GNU coreutils
  description: |
    uutils is an attempt at writing universal (as in cross-platform) CLI utilities in Rust.
    uutils aims to work on as many platforms as possible,
    to be able to use the same utils on Linux, Mac, Windows and other platforms.
    This ensures, for example, that scripts can be easily transferred between platforms.
    Rust was chosen not only because it is fast and safe,
    but is also excellent for writing cross-platform code.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://uutils.github.io/coreutils/docs/
  dev_url: https://github.com/uutils/coreutils

extra:
  recipe-maintainers:
    - sshockwave
