{% set name = "uutils-coreutils" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uutils/coreutils/archive/{{ version }}.tar.gz
  sha256: 5f0c3f97b807e72edccc844c6a685ec9862199f16a665df07de5b1d20ec21233

build:
  number: 0
  script_env:
    - CARGO_PROFILE_RELEASE_STRIP=symbols
    - CARGO_PROFILE_RELEASE_LTO=fat
    - LIBCLANG_PATH=$BUILD_PREFIX/lib  # [linux]
  ignore_run_exports_from:
    - {{ stdlib('c') }}  # [win]
    - {{ compiler('c') }}  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
    - {{ cdt('libselinux-devel') }}  # [linux]
    - clangdev  # [linux]
  run_constrained:
    - coreutils ==999999999
    - gnu-coreutils ==999999999
    - m2-coreutils ==999999999

test:
  commands:
    - coreutils --help
    - cat --help

about:
  home: https://uutils.github.io/coreutils/
  summary: Cross-platform Rust rewrite of the GNU coreutils
  description: |
    uutils is an attempt at writing universal (as in cross-platform) CLI utilities in Rust.
    uutils aims to work on as many platforms as possible,
    to be able to use the same utils on Linux, Mac, Windows and other platforms.
    This ensures, for example, that scripts can be easily transferred between platforms.
    Rust was chosen not only because it is fast and safe,
    but is also excellent for writing cross-platform code.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://uutils.github.io/coreutils/docs/
  dev_url: https://github.com/uutils/coreutils

extra:
  recipe-maintainers:
    - XhstormR
    - sshockwave
