schema_version: 1

context:
  name: uutils-coreutils
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/uutils/coreutils/archive/${{ version }}.tar.gz
  sha256: 83535e10c3273c31baa2f553dfa0ceb4148914e9c1a9c5b00d19fbda5b2d4d7d

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
    - if: linux
      then:
        - ${{ cdt('libselinux-devel') }}
        - clangdev
  ignore_run_exports:
    from_package:
      - if: win
        then:
          - ${{ stdlib('c') }}
          - ${{ compiler('c') }}
  run_constraints:
    - coreutils ==999999999
    - gnu-coreutils ==999999999
    - m2-coreutils ==999999999

tests:
  - script:
      - coreutils --help
      - cat --help

about:
  summary: Cross-platform Rust rewrite of the GNU coreutils
  description: |
    uutils is an attempt at writing universal (as in cross-platform) CLI utilities in Rust.
    uutils aims to work on as many platforms as possible,
    to be able to use the same utils on Linux, Mac, Windows and other platforms.
    This ensures, for example, that scripts can be easily transferred between platforms.
    Rust was chosen not only because it is fast and safe,
    but is also excellent for writing cross-platform code.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://uutils.github.io/coreutils/
  repository: https://github.com/uutils/coreutils
  documentation: https://uutils.github.io/coreutils/docs/

extra:
  recipe-maintainers:
    - XhstormR
    - sshockwave
