schema_version: 1

context:
  name: uutils-coreutils
  version: 0.0.30

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/uutils/coreutils/archive/${{ version }}.tar.gz
  sha256: 732c0ac646be7cc59a51cdfdb2d0ff1a4d2501c28f900a2d447c77729fdfca22
  patches:
    - 0001-GNUmakefile-support-CARGO_BUILD_TARGET.patch
    - 0002-GNUmakefile-fix-install-of-ln-to-PATH.patch

build:
  number: 0

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - make
    - cargo-bundle-licenses
  ignore_run_exports:
    by_name:
      - if: linux
        then:
          - libstdcxx-ng
          - libstdcxx
    from_package:
      - if: not linux
        then: ${{ compiler("cxx") | split | first }}
  run_constraints:
    - coreutils ==999999999
    - gnu-coreutils ==999999999

tests:
  - script:
    - coreutils --help
    - cat --help
  - package_contents:
      bin:
        - coreutils
        - cat

about:
  summary: Cross-platform Rust rewrite of the GNU coreutils
  description: |
    uutils is an attempt at writing universal (as in cross-platform) CLI utilities in Rust.
    uutils aims to work on as many platforms as possible,
    to be able to use the same utils on Linux, Mac, Windows and other platforms.
    This ensures, for example, that scripts can be easily transferred between platforms.
    Rust was chosen not only because it is fast and safe,
    but is also excellent for writing cross-platform code.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/uutils/coreutils
  repository: https://github.com/uutils/coreutils
  documentation: https://uutils.github.io/user/

extra:
  recipe-maintainers:
    - sshockwave
